language: ruby
rvm:
- 2.0.0
- 2.2.2
- 1.9.3
- jruby-19mode
- rbx-2
before_install:
- gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
- gem install bundler -v '< 2'

script:  
#  — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec

