language: ruby
rvm:
- 2.5.0
- jruby-19mode
- rbx-2

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - rake db:migrate
  - rake db:test:prepare

script:  
 — bundle exec rspec

